### ISSUE TITLE
Could not get temporary credentials: no valid AWS roles were returned

### ISSUE THREAD

**Issue by michelsk** [allcloud-io/clisso#267]
after running :
clisso get my-app
and entering the OTP from my MFA device, 
I'm getting the following error:
Could not get temporary credentials: no valid AWS roles were returned
using OKTA as an Idp , and in .clisso.yaml on the credentials-path , I'm not using credentials but using only config
The regular functionality of AWS SSO works as expected

**Comment by bitte-ein-bit** [comment]
version 0.16 and above feature logging. Can you add 
```
global:
    log:
        file: ~/.clisso-test.log
        level: trace
```
to your `~/.clisso.yaml` and check the log file
