### ISSUE TITLE
Add debug flag

### ISSUE THREAD

**Issue by johananl** [allcloud-io/clisso#74]
It could be very useful to have a `--debug` flag on Clisso which would cause the app to log for example HTTP requests.

**Comment by bitte-ein-bit** [comment]
Since 0.16, Clisso has a log functionality. Adding the below to the config file `~/.clisso.yaml` will enable it:
```
global:
    log:
        file: ~/.clisso-test.log
        level: trace
```
